<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsCheck" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Banking.Application\Banking.Application.csproj" />
    <ProjectReference Include="..\..\src\Banking.Contracts\Banking.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Banking.Domain\Banking.Domain.csproj" />
  </ItemGroup>

</Project>
