// <auto-generated />
using System;
using Banking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Banking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BankingDbContext))]
    [Migration("20260924055857_Ledger")]
    partial class Ledger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Banking.Domain.Ledger.LedgerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<bool>("AllowNegative")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_negative");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<bool>("HasMaterializedBalance")
                        .HasColumnType("boolean")
                        .HasColumnName("has_materialized_balance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("nature");

                    b.Property<string>("NormalBalance")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("normal_balance");

                    b.HasKey("Id")
                        .HasName("pk_ledger_accounts");

                    b.HasAlternateKey("Id", "CurrencyCode")
                        .HasName("ak_ledger_account_id_currency_code");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_accounts_account_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_accounts_code");

                    b.ToTable("ledger_accounts", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_ledger_accounts_customer_rules", "account_id IS NULL OR (nature = 'LIABILITY' AND normal_balance = 'C' AND NOT allow_negative)");

                            t.HasCheckConstraint("ck_ledger_accounts_materialized_only_for_customers", "has_materialized_balance = (account_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_ledger_accounts_nature", "nature IN ('ASSET', 'LIABILITY')");

                            t.HasCheckConstraint("ck_ledger_accounts_normal_balance", "normal_balance IN ('D', 'C')");
                        });
                });

            modelBuilder.Entity("Banking.Domain.Ledger.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("AccountSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("account_sequence");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<long?>("BalanceAfterMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after_minor");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("direction");

                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_account_id");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_ledger_entries");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_ledger_entries_transaction_id");

                    b.HasIndex("LedgerAccountId", "AccountSequence")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_entries_ledger_account_id_account_sequence");

                    b.HasIndex("LedgerAccountId", "CurrencyCode")
                        .HasDatabaseName("ix_ledger_entries_ledger_account_id_currency");

                    b.ToTable("ledger_entries", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_ledger_entries_amount_positive", "amount_minor > 0");

                            t.HasCheckConstraint("ck_ledger_entries_direction", "direction IN ('D', 'C')");

                            t.HasCheckConstraint("ck_ledger_entries_sequence_and_balance_together", "(account_sequence IS NULL) = (balance_after_minor IS NULL)");
                        });
                });

            modelBuilder.Entity("Banking.Domain.Ledger.LedgerTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<Guid?>("ReversesTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_transaction_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_ledger_transactions");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_transactions_external_id");

                    b.HasIndex("ReversesTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_transactions_reverses_transaction_id");

                    b.ToTable("ledger_transactions", "ledger");
                });

            modelBuilder.Entity("Banking.Infrastructure.Persistence.Configurations.AccountBalanceRecord", b =>
                {
                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_account_id");

                    b.Property<bool>("AllowNegative")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_negative");

                    b.Property<long>("BalanceMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_minor");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence");

                    b.Property<string>("NormalBalance")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("normal_balance");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("LedgerAccountId")
                        .HasName("pk_account_balances");

                    b.HasIndex("LedgerAccountId", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ix_account_balances_ledger_account_id_currency");

                    b.ToTable("account_balances", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_account_balances_non_negative", "allow_negative OR balance_minor >= 0");
                        });
                });

            modelBuilder.Entity("Banking.Domain.Ledger.LedgerEntry", b =>
                {
                    b.HasOne("Banking.Domain.Ledger.LedgerTransaction", null)
                        .WithMany("Entries")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_entries_ledger_transactions_transaction_id");

                    b.HasOne("Banking.Domain.Ledger.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("LedgerAccountId", "CurrencyCode")
                        .HasPrincipalKey("Id", "CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_entries_ledger_accounts_ledger_account_id_currency");
                });

            modelBuilder.Entity("Banking.Domain.Ledger.LedgerTransaction", b =>
                {
                    b.HasOne("Banking.Domain.Ledger.LedgerTransaction", null)
                        .WithOne()
                        .HasForeignKey("Banking.Domain.Ledger.LedgerTransaction", "ReversesTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ledger_transactions_ledger_transactions_reverses_transactio");
                });

            modelBuilder.Entity("Banking.Infrastructure.Persistence.Configurations.AccountBalanceRecord", b =>
                {
                    b.HasOne("Banking.Domain.Ledger.LedgerAccount", null)
                        .WithOne()
                        .HasForeignKey("Banking.Infrastructure.Persistence.Configurations.AccountBalanceRecord", "LedgerAccountId", "Currency")
                        .HasPrincipalKey("Banking.Domain.Ledger.LedgerAccount", "Id", "CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_balances_ledger_account_ledger_account_id_currency");
                });

            modelBuilder.Entity("Banking.Domain.Ledger.LedgerTransaction", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
