// <auto-generated />
using System;
using Banking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Banking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BankingDbContext))]
    partial class BankingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("account_number_seq", "accounts");

            modelBuilder.Entity("Banking.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("branch");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_account_id");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_accounts_customer_id");

                    b.HasIndex("LedgerAccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_ledger_account_id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_number");

                    b.ToTable("accounts", "accounts");
                });

            modelBuilder.Entity("Banking.Domain.Accounts.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("DocumentBlindIndex")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("document_blind_index");

                    b.Property<byte[]>("DocumentCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("document_ciphertext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("DocumentBlindIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_document_blind_index");

                    b.HasIndex("Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_subject");

                    b.ToTable("customers", "accounts");
                });

            modelBuilder.Entity("Banking.Domain.Ledger.LedgerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<bool>("AllowNegative")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_negative");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<bool>("HasMaterializedBalance")
                        .HasColumnType("boolean")
                        .HasColumnName("has_materialized_balance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("nature");

                    b.Property<string>("NormalBalance")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("normal_balance");

                    b.HasKey("Id")
                        .HasName("pk_ledger_accounts");

                    b.HasAlternateKey("Id", "CurrencyCode")
                        .HasName("ak_ledger_account_id_currency_code");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_accounts_account_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_accounts_code");

                    b.ToTable("ledger_accounts", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_ledger_accounts_customer_rules", "account_id IS NULL OR (nature = 'LIABILITY' AND normal_balance = 'C' AND NOT allow_negative)");

                            t.HasCheckConstraint("ck_ledger_accounts_materialized_only_for_customers", "has_materialized_balance = (account_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_ledger_accounts_nature", "nature IN ('ASSET', 'LIABILITY')");

                            t.HasCheckConstraint("ck_ledger_accounts_normal_balance", "normal_balance IN ('D', 'C')");
                        });
                });

            modelBuilder.Entity("Banking.Domain.Ledger.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("AccountSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("account_sequence");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<long?>("BalanceAfterMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after_minor");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("direction");

                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_account_id");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_ledger_entries");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_ledger_entries_transaction_id");

                    b.HasIndex("LedgerAccountId", "AccountSequence")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_entries_ledger_account_id_account_sequence");

                    b.HasIndex("LedgerAccountId", "CurrencyCode")
                        .HasDatabaseName("ix_ledger_entries_ledger_account_id_currency");

                    b.ToTable("ledger_entries", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_ledger_entries_amount_positive", "amount_minor > 0");

                            t.HasCheckConstraint("ck_ledger_entries_direction", "direction IN ('D', 'C')");

                            t.HasCheckConstraint("ck_ledger_entries_sequence_and_balance_together", "(account_sequence IS NULL) = (balance_after_minor IS NULL)");
                        });
                });

            modelBuilder.Entity("Banking.Domain.Ledger.LedgerTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<Guid?>("ReversesTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_transaction_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_ledger_transactions");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_transactions_external_id");

                    b.HasIndex("ReversesTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_transactions_reverses_transaction_id");

                    b.ToTable("ledger_transactions", "ledger");
                });

            modelBuilder.Entity("Banking.Domain.Payments.Deposit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("LedgerTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_transaction_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_deposits");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_deposits_account_id");

                    b.HasIndex("RequestedBy", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_deposits_requested_by_idempotency_key");

                    b.ToTable("deposits", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_deposits_amount_positive", "amount_minor > 0");
                        });
                });

            modelBuilder.Entity("Banking.Infrastructure.Persistence.Configurations.AccountBalanceRecord", b =>
                {
                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_account_id");

                    b.Property<bool>("AllowNegative")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_negative");

                    b.Property<long>("BalanceMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_minor");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence");

                    b.Property<string>("NormalBalance")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("normal_balance");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("LedgerAccountId")
                        .HasName("pk_account_balances");

                    b.HasIndex("LedgerAccountId", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ix_account_balances_ledger_account_id_currency");

                    b.ToTable("account_balances", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_account_balances_non_negative", "allow_negative OR balance_minor >= 0");
                        });
                });

            modelBuilder.Entity("Banking.Infrastructure.Persistence.Configurations.IdempotencyKeyRecord", b =>
                {
                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_id");

                    b.Property<string>("Operation")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("operation");

                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("RequestHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("request_hash");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.HasKey("ClientId", "Operation", "Key")
                        .HasName("pk_idempotency_keys");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_keys_expires_at");

                    b.ToTable("idempotency_keys", "platform");
                });

            modelBuilder.Entity("Banking.Infrastructure.Persistence.Configurations.LimitUsageRecord", b =>
                {
                    b.Property<string>("LimitKind")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("limit_kind");

                    b.Property<string>("Subject")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject");

                    b.Property<DateOnly>("UsageDate")
                        .HasColumnType("date")
                        .HasColumnName("usage_date");

                    b.Property<long>("UsedMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("used_minor");

                    b.HasKey("LimitKind", "Subject", "UsageDate")
                        .HasName("pk_limit_usage");

                    b.ToTable("limit_usage", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_limit_usage_non_negative", "used_minor >= 0");
                        });
                });

            modelBuilder.Entity("Banking.Domain.Accounts.Account", b =>
                {
                    b.HasOne("Banking.Domain.Accounts.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_customer_customer_id");
                });

            modelBuilder.Entity("Banking.Domain.Ledger.LedgerEntry", b =>
                {
                    b.HasOne("Banking.Domain.Ledger.LedgerTransaction", null)
                        .WithMany("Entries")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_entries_ledger_transactions_transaction_id");

                    b.HasOne("Banking.Domain.Ledger.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("LedgerAccountId", "CurrencyCode")
                        .HasPrincipalKey("Id", "CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_entries_ledger_accounts_ledger_account_id_currency");
                });

            modelBuilder.Entity("Banking.Domain.Ledger.LedgerTransaction", b =>
                {
                    b.HasOne("Banking.Domain.Ledger.LedgerTransaction", null)
                        .WithOne()
                        .HasForeignKey("Banking.Domain.Ledger.LedgerTransaction", "ReversesTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ledger_transactions_ledger_transactions_reverses_transactio");
                });

            modelBuilder.Entity("Banking.Domain.Payments.Deposit", b =>
                {
                    b.HasOne("Banking.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deposits_accounts_account_id");
                });

            modelBuilder.Entity("Banking.Infrastructure.Persistence.Configurations.AccountBalanceRecord", b =>
                {
                    b.HasOne("Banking.Domain.Ledger.LedgerAccount", null)
                        .WithOne()
                        .HasForeignKey("Banking.Infrastructure.Persistence.Configurations.AccountBalanceRecord", "LedgerAccountId", "Currency")
                        .HasPrincipalKey("Banking.Domain.Ledger.LedgerAccount", "Id", "CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_balances_ledger_account_ledger_account_id_currency");
                });

            modelBuilder.Entity("Banking.Domain.Ledger.LedgerTransaction", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
