// <auto-generated />
using System;
using Banking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Banking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BankingDbContext))]
    partial class BankingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("account_number_seq", "accounts");

            modelBuilder.Entity("Banking.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("branch");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_account_id");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_accounts_customer_id");

                    b.HasIndex("LedgerAccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_ledger_account_id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_number");

                    b.ToTable("accounts", "accounts");
                });

            modelBuilder.Entity("Banking.Domain.Accounts.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("DocumentBlindIndex")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("document_blind_index");

                    b.Property<byte[]>("DocumentCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("document_ciphertext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("DocumentBlindIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_document_blind_index");

                    b.HasIndex("Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_subject");

                    b.ToTable("customers", "accounts");
                });

            modelBuilder.Entity("Banking.Domain.Ledger.LedgerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<bool>("AllowNegative")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_negative");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<bool>("HasMaterializedBalance")
                        .HasColumnType("boolean")
                        .HasColumnName("has_materialized_balance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("nature");

                    b.Property<string>("NormalBalance")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("normal_balance");

                    b.HasKey("Id")
                        .HasName("pk_ledger_accounts");

                    b.HasAlternateKey("Id", "CurrencyCode")
                        .HasName("ak_ledger_account_id_currency_code");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_accounts_account_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_accounts_code");

                    b.ToTable("ledger_accounts", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_ledger_accounts_customer_rules", "account_id IS NULL OR (nature = 'LIABILITY' AND normal_balance = 'C' AND NOT allow_negative)");

                            t.HasCheckConstraint("ck_ledger_accounts_materialized_only_for_customers", "has_materialized_balance = (account_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_ledger_accounts_nature", "nature IN ('ASSET', 'LIABILITY')");

                            t.HasCheckConstraint("ck_ledger_accounts_normal_balance", "normal_balance IN ('D', 'C')");
                        });
                });

            modelBuilder.Entity("Banking.Domain.Ledger.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("AccountSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("account_sequence");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<long?>("BalanceAfterMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after_minor");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("direction");

                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_account_id");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_ledger_entries");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_ledger_entries_transaction_id");

                    b.HasIndex("LedgerAccountId", "AccountSequence")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_entries_ledger_account_id_account_sequence");

                    b.HasIndex("LedgerAccountId", "CurrencyCode")
                        .HasDatabaseName("ix_ledger_entries_ledger_account_id_currency");

                    b.ToTable("ledger_entries", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_ledger_entries_amount_positive", "amount_minor > 0");

                            t.HasCheckConstraint("ck_ledger_entries_direction", "direction IN ('D', 'C')");

                            t.HasCheckConstraint("ck_ledger_entries_sequence_and_balance_together", "(account_sequence IS NULL) = (balance_after_minor IS NULL)");
                        });
                });

            modelBuilder.Entity("Banking.Domain.Ledger.LedgerTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<Guid?>("ReversesTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_transaction_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_ledger_transactions");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_transactions_external_id");

                    b.HasIndex("ReversesTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_ledger_transactions_reverses_transaction_id");

                    b.ToTable("ledger_transactions", "ledger");
                });

            modelBuilder.Entity("Banking.Domain.Payments.Deposit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("decided_by");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("LedgerTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_transaction_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_deposits");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_deposits_account_id");

                    b.HasIndex("RequestedBy", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_deposits_requested_by_idempotency_key");

                    b.ToTable("deposits", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_deposits_amount_positive", "amount_minor > 0");
                        });
                });

            modelBuilder.Entity("Banking.Domain.Payments.ExternalTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("DestinationAccount")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("destination_account");

                    b.Property<string>("DestinationBank")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("destination_bank");

                    b.Property<string>("DestinationBranch")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("destination_branch");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset?>("LastSubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_submitted_at");

                    b.Property<DateTimeOffset?>("NextCheckAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_check_at");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("requested_by");

                    b.Property<bool>("RequiresManualReview")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_manual_review");

                    b.Property<Guid>("SourceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_account_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("SubmitAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("submit_attempts");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_external_transfers");

                    b.HasIndex("SourceAccountId")
                        .HasDatabaseName("ix_external_transfers_source_account_id");

                    b.HasIndex("RequestedBy", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_external_transfers_requested_by_idempotency_key");

                    b.HasIndex("Status", "NextCheckAt")
                        .HasDatabaseName("ix_external_transfers_status_next_check_at");

                    b.ToTable("external_transfers", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_external_transfers_amount_positive", "amount_minor > 0");
                        });
                });

            modelBuilder.Entity("Banking.Domain.Payments.InternalTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("description");

                    b.Property<Guid>("DestinationAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_account_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("LedgerTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_transaction_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("requested_by");

                    b.Property<Guid>("SourceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_account_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_internal_transfers");

                    b.HasIndex("DestinationAccountId")
                        .HasDatabaseName("ix_internal_transfers_destination_account_id");

                    b.HasIndex("SourceAccountId")
                        .HasDatabaseName("ix_internal_transfers_source_account_id");

                    b.HasIndex("RequestedBy", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_internal_transfers_requested_by_idempotency_key");

                    b.ToTable("internal_transfers", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_internal_transfers_amount_positive", "amount_minor > 0");

                            t.HasCheckConstraint("ck_internal_transfers_distinct_accounts", "source_account_id <> destination_account_id");
                        });
                });

            modelBuilder.Entity("Banking.Domain.Payments.ManualResolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("decided_by");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("evidence");

                    b.Property<Guid>("ExternalTransferId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_transfer_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_manual_resolutions");

                    b.HasIndex("ExternalTransferId")
                        .IsUnique()
                        .HasDatabaseName("ix_manual_resolutions_external_transfer_id")
                        .HasFilter("status = 'PendingApproval'");

                    b.ToTable("manual_resolutions", "payments");
                });

            modelBuilder.Entity("Banking.Domain.Payments.TransferReversal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("decided_by");

                    b.Property<Guid?>("LedgerTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_transaction_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_id");

                    b.HasKey("Id")
                        .HasName("pk_transfer_reversals");

                    b.HasIndex("TransferId")
                        .IsUnique()
                        .HasDatabaseName("ix_transfer_reversals_transfer_id")
                        .HasFilter("status IN ('PendingApproval', 'Completed')");

                    b.ToTable("transfer_reversals", "payments");
                });

            modelBuilder.Entity("Banking.Infrastructure.Persistence.Configurations.AccountBalanceRecord", b =>
                {
                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_account_id");

                    b.Property<bool>("AllowNegative")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_negative");

                    b.Property<long>("BalanceMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_minor");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence");

                    b.Property<string>("NormalBalance")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("normal_balance");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("LedgerAccountId")
                        .HasName("pk_account_balances");

                    b.HasIndex("LedgerAccountId", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ix_account_balances_ledger_account_id_currency");

                    b.ToTable("account_balances", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_account_balances_non_negative", "allow_negative OR balance_minor >= 0");
                        });
                });

            modelBuilder.Entity("Banking.Infrastructure.Persistence.Configurations.AuditLogRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("operation");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("outcome");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("resource_type");

                    b.Property<string>("TraceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("ResourceId")
                        .HasDatabaseName("ix_audit_log_resource_id");

                    b.ToTable("audit_log", "platform");
                });

            modelBuilder.Entity("Banking.Infrastructure.Persistence.Configurations.IdempotencyKeyRecord", b =>
                {
                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_id");

                    b.Property<string>("Operation")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("operation");

                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("RequestHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("request_hash");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.HasKey("ClientId", "Operation", "Key")
                        .HasName("pk_idempotency_keys");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_keys_expires_at");

                    b.ToTable("idempotency_keys", "platform");
                });

            modelBuilder.Entity("Banking.Infrastructure.Persistence.Configurations.InboxMessageRecord", b =>
                {
                    b.Property<string>("Consumer")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("consumer");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Consumer", "EventId")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "platform");
                });

            modelBuilder.Entity("Banking.Infrastructure.Persistence.Configurations.LimitUsageRecord", b =>
                {
                    b.Property<string>("LimitKind")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("limit_kind");

                    b.Property<string>("Subject")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject");

                    b.Property<DateOnly>("UsageDate")
                        .HasColumnType("date")
                        .HasColumnName("usage_date");

                    b.Property<long>("UsedMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("used_minor");

                    b.HasKey("LimitKind", "Subject", "UsageDate")
                        .HasName("pk_limit_usage");

                    b.ToTable("limit_usage", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_limit_usage_non_negative", "used_minor >= 0");
                        });
                });

            modelBuilder.Entity("Banking.Infrastructure.Persistence.Configurations.NotificationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Amount")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("kind");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("AccountId", "CreatedAt")
                        .HasDatabaseName("ix_notifications_account_id_created_at");

                    b.HasIndex("EventId", "AccountId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_notifications_event_id_account_id_kind");

                    b.ToTable("notifications", "notifications");
                });

            modelBuilder.Entity("Banking.Infrastructure.Persistence.Configurations.OutboxMessageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_parent");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_messages_status_next_attempt_at")
                        .HasFilter("status = 'Pending'");

                    b.ToTable("outbox_messages", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_messages_status", "status IN ('Pending', 'Published', 'DeadLettered')");
                        });
                });

            modelBuilder.Entity("Banking.Domain.Accounts.Account", b =>
                {
                    b.HasOne("Banking.Domain.Accounts.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_customer_customer_id");
                });

            modelBuilder.Entity("Banking.Domain.Ledger.LedgerEntry", b =>
                {
                    b.HasOne("Banking.Domain.Ledger.LedgerTransaction", null)
                        .WithMany("Entries")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_entries_ledger_transactions_transaction_id");

                    b.HasOne("Banking.Domain.Ledger.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("LedgerAccountId", "CurrencyCode")
                        .HasPrincipalKey("Id", "CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_entries_ledger_accounts_ledger_account_id_currency");
                });

            modelBuilder.Entity("Banking.Domain.Ledger.LedgerTransaction", b =>
                {
                    b.HasOne("Banking.Domain.Ledger.LedgerTransaction", null)
                        .WithOne()
                        .HasForeignKey("Banking.Domain.Ledger.LedgerTransaction", "ReversesTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ledger_transactions_ledger_transactions_reverses_transactio");
                });

            modelBuilder.Entity("Banking.Domain.Payments.Deposit", b =>
                {
                    b.HasOne("Banking.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deposits_accounts_account_id");
                });

            modelBuilder.Entity("Banking.Domain.Payments.ExternalTransfer", b =>
                {
                    b.HasOne("Banking.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("SourceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_external_transfers_accounts_source_account_id");
                });

            modelBuilder.Entity("Banking.Domain.Payments.InternalTransfer", b =>
                {
                    b.HasOne("Banking.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("DestinationAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_internal_transfers_accounts_destination_account_id");

                    b.HasOne("Banking.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("SourceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_internal_transfers_accounts_source_account_id");
                });

            modelBuilder.Entity("Banking.Domain.Payments.ManualResolution", b =>
                {
                    b.HasOne("Banking.Domain.Payments.ExternalTransfer", null)
                        .WithMany()
                        .HasForeignKey("ExternalTransferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_manual_resolutions_external_transfers_external_transfer_id");
                });

            modelBuilder.Entity("Banking.Domain.Payments.TransferReversal", b =>
                {
                    b.HasOne("Banking.Domain.Payments.InternalTransfer", null)
                        .WithMany()
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transfer_reversals_internal_transfers_transfer_id");
                });

            modelBuilder.Entity("Banking.Infrastructure.Persistence.Configurations.AccountBalanceRecord", b =>
                {
                    b.HasOne("Banking.Domain.Ledger.LedgerAccount", null)
                        .WithOne()
                        .HasForeignKey("Banking.Infrastructure.Persistence.Configurations.AccountBalanceRecord", "LedgerAccountId", "Currency")
                        .HasPrincipalKey("Banking.Domain.Ledger.LedgerAccount", "Id", "CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_balances_ledger_account_ledger_account_id_currency");
                });

            modelBuilder.Entity("Banking.Domain.Ledger.LedgerTransaction", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
